pluginManagement {
  repositories {
    gradlePluginPortal()
    maven {
      name = 'Fabric'
      url = 'https://maven.fabricmc.net/'
    }
    maven {
      name = 'NeoForge'
      url = 'https://maven.neoforged.net/releases/'
    }
    maven {
      name = 'Forge'
      url = 'https://maven.minecraftforge.net/'
    }

    plugins {
      id 'fabric-loom' version "${fabric_loom}"
    }
  }
}

rootProject.name = 'Eco Stack Manager 1.21.8'
include("Common", "Fabric", "Forge", "NeoForge")
