plugins {
  id 'maven-publish'
  id 'net.neoforged.moddev' version '2.0.72'
}

base {
  archivesName = "${project.mod_id}-common-${project.minecraft_version}"
}

neoForge {
  neoFormVersion = neo_form_version
}

dependencies {}

publishing {
  publications {
    mavenJava(MavenPublication) {
      groupId project.group
      artifactId project.archivesBaseName
      version project.version
      artifact jar
    }
  }
}
